name: eduquest_mobile
description: "EduQuest: Platform Belajar Kolaboratif"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  crypto: ^3.0.3
  http: ^1.2.0
  image_picker: ^1.2.3
  intl: ^0.20.3
  share_plus: ^12.0.2
  url_launcher: ^6.3.2
  file_picker: ^8.1.4
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/eduquestlogo1.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eduquestlogo.png"